import { db } from "@/lib/db";
import { embeddingManager } from "@/lib/providers/embeddings/manager";
import { getVectorStore } from "@/lib/providers/vector";
import type { ToolContext, ToolDefinitionRuntime, ToolExecutionResult } from "./types";
const BUILTINS = [
  { key: "calculator", name: "ماشین حساب", description: "محاسبات ریاضی ساده را انجام می‌دهد.", inputSchema: JSON.stringify({ type: "object", properties: { expression: { type: "string" } }, required: ["expression"] }), permissions: "READ" },
  { key: "knowledge_search", name: "جستجوی دانش", description: "در دانش آماده ایجنت جستجو می‌کند.", inputSchema: JSON.stringify({ type: "object", properties: { query: { type: "string" } }, required: ["query"] }), permissions: "READ" }
];
export async function ensureBuiltinTools() { for (const tool of BUILTINS) await db.toolDefinition.upsert({ where: { key: tool.key }, update: { name: tool.name, description: tool.description, inputSchema: tool.inputSchema, permissions: tool.permissions, enabled: true }, create: { ...tool, kind: "builtin" } }); }
export async function listAgentTools(agentId: string): Promise<ToolDefinitionRuntime[]> { await ensureBuiltinTools(); const rows = await db.agentTool.findMany({ where: { agentId, enabled: true }, include: { tool: true } }); return rows.filter(r => r.tool.enabled).map(r => ({ id: r.tool.id, key: r.tool.key, name: r.tool.name, description: r.tool.description, inputSchema: r.tool.inputSchema, permissions: r.tool.permissions, kind: r.tool.kind })); }
function safeCalculate(expression: string): number { if (!/^[0-9+\\-*/().%\\s]+$/.test(expression) || expression.length > 200) throw new Error("عبارت ریاضی نامعتبر است."); const value = Function('"use strict"; return (' + expression + ')')(); if (typeof value !== "number" || !Number.isFinite(value)) throw new Error("نتیجه محاسبه معتبر نیست."); return value; }
async function knowledgeSearch(query: string, ctx: ToolContext) { const sources = await db.knowledgeSource.findMany({ where: { agentId: ctx.agentId, status: "ready" }, select: { id: true } }); if (!sources.length) return []; const embedder = embeddingManager.resolve(); if (!embedder) return []; const vector = await embedder.embedText(query.slice(0, 1000)); const results = await getVectorStore().search(ctx.agentId, vector, 5); const allowed = new Set(sources.map(s => s.id)); const chunks = await db.knowledgeChunk.findMany({ where: { id: { in: results.map(r => r.id) }, agentId: ctx.agentId, workspaceId: ctx.workspaceId, sourceId: { in: [...allowed] } }, select: { id: true } }); const valid = new Set(chunks.map(c => c.id)); return results.filter(r => valid.has(r.id)).map(r => ({ score: r.score, text: String(r.payload?.text ?? ""), documentName: r.payload?.documentName ?? "—", page: r.payload?.page ?? null })).slice(0, 5); }
export async function executeTool(tool: ToolDefinitionRuntime, args: Record<string, unknown>, ctx: ToolContext): Promise<ToolExecutionResult> { try { if (tool.key === "calculator") return { ok: true, output: safeCalculate(String(args.expression ?? "")) }; if (tool.key === "knowledge_search") return { ok: true, output: await knowledgeSearch(String(args.query ?? ""), ctx) }; return { ok: false, output: null, error: "این ابزار executor ندارد." }; } catch (error) { return { ok: false, output: null, error: error instanceof Error ? error.message : "خطای اجرای ابزار" }; } }
