"use client";
import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Bot, Link2, Plus, RefreshCw, ShieldCheck, Trash2, Users, Wifi } from 'lucide-react';
import { toast } from 'sonner';
import { api, type TelegramBotDto } from '@/lib/cortex-client';
import { useCortexStore } from '@/components/cortex/store';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { cn } from '@/lib/utils';

export function TelegramView(){
 const workspaceId=useCortexStore(s=>s.activeWorkspaceId); const qc=useQueryClient(); const [open,setOpen]=useState(false); const [selected,setSelected]=useState<TelegramBotDto|null>(null);
 const botsQ=useQuery({queryKey:['telegram-bots',workspaceId],queryFn:()=>api.getTelegramBots(workspaceId??undefined),enabled:!!workspaceId}); const agentsQ=useQuery({queryKey:['agents',workspaceId],queryFn:()=>api.getAgents(workspaceId??undefined),enabled:!!workspaceId});
 const bots=botsQ.data?.bots??[]; const agents=agentsQ.data?.agents??[];
 const create=useMutation({mutationFn:(v:{workspaceId?:string;agentId:string;name:string;token:string;mode:'webhook'|'polling'})=>api.createTelegramBot(v),onSuccess:()=>{toast.success('ربات اضافه شد');setOpen(false);qc.invalidateQueries({queryKey:['telegram-bots']})},onError:e=>toast.error(e.message)});
 const del=useMutation({mutationFn:api.deleteTelegramBot,onSuccess:()=>{toast.success('ربات حذف شد');qc.invalidateQueries({queryKey:['telegram-bots']})},onError:e=>toast.error(e.message)});
 return <div className="space-y-8">
   <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="cortex-kicker">مرکز اتصال</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">تلگرام</h2><p className="mt-2 max-w-2xl text-sm leading-7 text-muted-foreground">ربات‌های واقعی خود را به ایجنت‌های Cortex وصل کنید؛ احراز شماره، دسترسی کاربران و پاسخ‌گویی با همان RAG.</p></div><Button onClick={()=>setOpen(true)}><Plus/> اتصال ربات</Button></div>
   <div className="grid gap-5 lg:grid-cols-3"><Metric title="ربات‌ها" value={bots.length} icon={<Bot/>}/><Metric title="اتصال فعال" value={bots.filter(b=>b.status==='connected').length} icon={<Wifi/>}/><Metric title="کاربران شناخته‌شده" value={bots.reduce((n,b)=>n+b.usersCount,0)} icon={<Users/>}/></div>
   {bots.length===0?<Card className="cortex-panel"><CardContent className="py-20 text-center"><Bot className="mx-auto size-12 text-primary/70"/><h3 className="mt-5 text-lg font-semibold">هنوز رباتی متصل نیست</h3><p className="mt-2 text-sm text-muted-foreground">یک BotFather token وارد کنید و آن را به ایجنت موردنظر وصل کنید.</p></CardContent></Card>:<div className="grid gap-5 lg:grid-cols-2">{bots.map(bot=><button key={bot.id} onClick={()=>setSelected(bot)} className="text-start"><Card className="cortex-panel h-full transition-transform duration-200 hover:-translate-y-1 hover:border-primary/40"><CardContent className="p-5"><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><div className="cortex-icon-box"><Bot/></div><div><p className="font-semibold">{bot.name}</p><p className="text-xs text-muted-foreground">@{bot.username??'—'} · {bot.agentName}</p></div></div><Badge className={cn('font-normal',bot.status==='connected'?'border-emerald-400/20 bg-emerald-400/10 text-emerald-300':'border-amber-400/20 bg-amber-400/10 text-amber-200')}>{bot.status==='connected'?'متصل':bot.status}</Badge></div><div className="mt-6 grid grid-cols-2 gap-3"><Mini label="حالت" value={bot.mode==='webhook'?'Webhook':'Polling'}/><Mini label="کاربر" value={String(bot.usersCount)}/></div>{bot.lastError&&<p className="mt-4 rounded-xl border border-destructive/20 bg-destructive/5 p-3 text-xs text-destructive">{bot.lastError}</p>}</CardContent></Card></button>)}</div>}
   <Dialog open={open} onOpenChange={setOpen}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>اتصال ربات تلگرام</DialogTitle><DialogDescription>توکن BotFather را وارد کنید. توکن در سمت سرور رمزنگاری می‌شود.</DialogDescription></DialogHeader><CreateBotForm agents={agents} workspaceId={workspaceId??undefined} pending={create.isPending} onSubmit={v=>create.mutate(v)} /></DialogContent></Dialog>
   {selected&&<BotDetail bot={selected} onClose={()=>setSelected(null)} onDelete={()=>{del.mutate(selected.id);setSelected(null)}} />}
 </div>
}
function CreateBotForm({agents,workspaceId,pending,onSubmit}:{agents:any[];workspaceId?:string;pending:boolean;onSubmit:(v:any)=>void}){const [name,setName]=useState('ربات Cortex');const [token,setToken]=useState('');const [agentId,setAgentId]=useState(agents[0]?.id??'');const [mode,setMode]=useState<'webhook'|'polling'>('webhook');return <form className="space-y-4" onSubmit={e=>{e.preventDefault();onSubmit({workspaceId,agentId,name,token,mode})}}><div><label className="text-xs text-muted-foreground">نام</label><Input value={name} onChange={e=>setName(e.target.value)} className="mt-2"/></div><div><label className="text-xs text-muted-foreground">Bot Token</label><Input dir="ltr" value={token} onChange={e=>setToken(e.target.value)} placeholder="123456:AA..." className="mt-2"/></div><div><label className="text-xs text-muted-foreground">ایجنت</label><Select value={agentId} onValueChange={setAgentId}><SelectTrigger className="mt-2"><SelectValue/></SelectTrigger><SelectContent>{agents.map(a=><SelectItem key={a.id} value={a.id}>{a.name}</SelectItem>)}</SelectContent></Select></div><div><label className="text-xs text-muted-foreground">روش دریافت</label><Select value={mode} onValueChange={v=>setMode(v as any)}><SelectTrigger className="mt-2"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="webhook">Webhook — مناسب Production</SelectItem><SelectItem value="polling">Polling — مناسب تست</SelectItem></SelectContent></Select></div><DialogFooter><Button type="submit" disabled={pending||!token||!agentId}>{pending?'در حال اتصال…':'اتصال ربات'}</Button></DialogFooter></form>}
function BotDetail({bot,onClose,onDelete}:{bot:TelegramBotDto;onClose:()=>void;onDelete:()=>void}){const {data}=useQuery({queryKey:['allowlist',bot.id],queryFn:()=>api.getTelegramAllowlist(bot.id)});const [phone,setPhone]=useState('');const [name,setName]=useState('');const qc=useQueryClient();const add=useMutation({mutationFn:()=>api.addTelegramAllowlist(bot.id,{phoneNumber:phone,displayName:name}),onSuccess:()=>{setPhone('');setName('');qc.invalidateQueries({queryKey:['allowlist',bot.id]});toast.success('کاربر مجاز شد')},onError:e=>toast.error(e.message)});return <Dialog open onOpenChange={v=>!v&&onClose()}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>{bot.name}</DialogTitle><DialogDescription>فهرست دسترسی کاربران این ربات</DialogDescription></DialogHeader><div className="grid gap-5 md:grid-cols-2"><Card className="border-white/5 bg-white/[.02]"><CardHeader><CardTitle className="text-sm">افزودن شماره مجاز</CardTitle></CardHeader><CardContent className="space-y-3"><Input dir="ltr" placeholder="+98912..." value={phone} onChange={e=>setPhone(e.target.value)}/><Input placeholder="نام نمایشی" value={name} onChange={e=>setName(e.target.value)}/><Button className="w-full" disabled={!phone||add.isPending} onClick={()=>add.mutate()}><ShieldCheck/> افزودن به allowlist</Button></CardContent></Card><Card className="border-white/5 bg-white/[.02]"><CardHeader><CardTitle className="text-sm">کاربران مجاز</CardTitle></CardHeader><CardContent>{(data?.entries??[]).length===0?<p className="text-sm text-muted-foreground">موردی ثبت نشده است.</p>:<div className="space-y-2">{data?.entries.map(e=><div key={e.id} className="flex items-center justify-between rounded-xl border p-3 text-sm"><div><p>{e.displayName||'بدون نام'}</p><p dir="ltr" className="text-xs text-muted-foreground">{e.phoneNumber}</p></div><Button size="icon" variant="ghost" onClick={()=>api.removeTelegramAllowlist(bot.id,e.id).then(()=>qc.invalidateQueries({queryKey:['allowlist',bot.id]})).catch(e=>toast.error(e.message))}><Trash2 className="size-4 text-destructive"/></Button></div>)}</div>}</CardContent></Card></div><DialogFooter className="justify-between"><Button variant="ghost" onClick={onClose}><Link2/> بستن</Button><Button variant="destructive" onClick={onDelete}><Trash2/> حذف ربات</Button></DialogFooter></DialogContent></Dialog>}
function Metric({title,value,icon}:{title:string;value:number;icon:any}){return <Card className="cortex-panel"><CardContent className="flex items-center gap-4 p-5"><div className="cortex-icon-box">{icon}</div><div><p className="text-2xl font-semibold">{value}</p><p className="text-xs text-muted-foreground">{title}</p></div></CardContent></Card>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-white/5 bg-black/10 p-3"><p className="text-[11px] text-muted-foreground">{label}</p><p className="mt-1 text-sm font-medium">{value}</p></div>}
