"use client";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { GitBranch, Plus, Play, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { api } from "@/lib/cortex-client";
import { useCortexStore } from "@/components/cortex/store";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
export function WorkflowsView(){const workspaceId=useCortexStore(s=>s.activeWorkspaceId);const qc=useQueryClient();const [name,setName]=useState("");const {data,isPending}=useQuery({queryKey:["workflows",workspaceId],queryFn:()=>api.getWorkflows(workspaceId??undefined),enabled:!!workspaceId});const create=useMutation({mutationFn:()=>api.createWorkflow({workspaceId:workspaceId??undefined,name}),onSuccess:()=>{setName("");qc.invalidateQueries({queryKey:["workflows",workspaceId]});toast.success("Workflow ساخته شد");},onError:(e:Error)=>toast.error(e.message)});const del=useMutation({mutationFn:(id:string)=>api.deleteWorkflow(id),onSuccess:()=>qc.invalidateQueries({queryKey:["workflows",workspaceId]}),onError:(e:Error)=>toast.error(e.message)});const workflows=data?.workflows??[];return <div className="space-y-6"><div className="flex flex-col gap-3 sm:flex-row"><Input value={name} onChange={e=>setName(e.target.value)} placeholder="نام Workflow جدید" onKeyDown={e=>{if(e.key==="Enter"&&name.trim())create.mutate()}}/><Button disabled={!name.trim()||create.isPending} onClick={()=>create.mutate()}><Plus/>ساخت Workflow</Button></div>{isPending?<Skeleton className="h-40 rounded-xl"/>:<div className="grid gap-4 lg:grid-cols-2">{workflows.map(w=><Card key={w.id} className="rounded-xl"><CardHeader><div className="flex items-center justify-between gap-3"><div><CardTitle className="text-base">{w.name}</CardTitle><CardDescription>{w.agent?.name??"بدون Agent"} · {w._count?.executions??0} اجرا</CardDescription></div><Badge variant="outline">{w.status}</Badge></div></CardHeader><CardContent><div className="flex flex-wrap items-center gap-2 rounded-xl border bg-muted/30 p-4"><span className="rounded-lg border bg-card px-3 py-2 text-xs">Trigger</span><span>→</span><span className="rounded-lg border bg-card px-3 py-2 text-xs">AI Agent</span><span>→</span><span className="rounded-lg border bg-card px-3 py-2 text-xs">Response</span></div><div className="mt-4 flex justify-end"><Button variant="ghost" size="sm" className="text-destructive" onClick={()=>del.mutate(w.id)}><Trash2/>حذف</Button></div></CardContent></Card>)}{workflows.length===0&&<Card className="rounded-xl lg:col-span-2"><CardContent className="flex flex-col items-center justify-center py-16 text-center"><GitBranch className="mb-3 size-8 text-primary"/><p className="font-medium">هنوز Workflow ندارید</p><p className="mt-1 text-sm text-muted-foreground">اولین Workflow واقعی Cortex را بسازید.</p></CardContent></Card>}</div>}</div>}
