import { randomBytes } from "@/lib/server/random";
import { db } from "@/lib/db";
import { applyCors, jsonError, jsonOk, readJson, toErrorResponse } from "@/lib/server/http";
import { requireSession, assertWorkspaceAccess } from "@/lib/server/auth";
import { encryptSecret, decryptSecret } from "@/lib/server/secrets";
import { audit } from "@/lib/server/audit";
import { deleteWebhook, getBotInfo, setWebhook } from "@/lib/telegram/service";
import { loadAgentForSession } from "@/lib/server/access";

export const dynamic = "force-dynamic";
type Params={params:Promise<{id:string}>};
function serialize(b:any){return{id:b.id,name:b.name,agentId:b.agentId,agentName:b.agent.name,username:b.username,status:b.status,mode:b.mode,lastError:b.lastError,lastSeenAt:b.lastSeenAt?.toISOString()??null,createdAt:b.createdAt.toISOString(),updatedAt:b.updatedAt.toISOString(),allowlistCount:b._count.allowlist,usersCount:b._count.users}}
async function load(session:any,id:string){const bot=await db.telegramBot.findUnique({where:{id},include:{agent:{select:{name:true}},_count:{select:{allowlist:true,users:true}}}});if(!bot)throw Object.assign(new Error("ربات تلگرام یافت نشد."),{status:404});assertWorkspaceAccess(session,bot.workspaceId);return bot;}
export async function GET(req:Request,{params}:Params){try{const s=await requireSession(req);return applyCors(jsonOk({bot:serialize(await load(s,(await params).id))}),req.headers.get('origin'));}catch(e){return toErrorResponse(e)}}
export async function PATCH(req:Request,{params}:Params){try{const s=await requireSession(req);const id=(await params).id;const bot=await load(s,id);const m=assertWorkspaceAccess(s,bot.workspaceId);if(!['owner','admin'].includes(m.role))throw Object.assign(new Error('دسترسی مدیریت ربات ندارید.'),{status:403});const b=await readJson<Record<string,unknown>>(req);const data:any={};if(typeof b.name==='string'&&b.name.trim())data.name=b.name.trim().slice(0,80);if(typeof b.mode==='string'&&b.mode==='polling')return applyCors(jsonError("در نسخه فعلی اتصال Telegram فقط با Webhook پشتیبانی می‌شود.",400),req.headers.get('origin'));if(typeof b.mode==='string'&&b.mode!=='webhook')return applyCors(jsonError("حالت اتصال نامعتبر است.",400),req.headers.get('origin'));if(typeof b.agentId==='string'&&b.agentId){
  const targetAgent=await loadAgentForSession(s,b.agentId);
  if(targetAgent.workspaceId!==bot.workspaceId){
    throw Object.assign(new Error('ایجنت انتخاب‌شده متعلق به همین فضای کاری نیست.'),{status:403});
  }
  data.agentId=targetAgent.id;
}let token=decryptSecret(bot.tokenEncrypted);if(typeof b.token==='string'&&b.token.trim()){const candidate=b.token.trim();let info:any;try{info=await getBotInfo(candidate);}catch(e){return applyCors(jsonError('توکن جدید معتبر نیست: '+(e instanceof Error?e.message:'خطای نامشخص'),502),req.headers.get('origin'));}data.tokenEncrypted=encryptSecret(candidate);data.username=info?.username??null;token=candidate;}const updated=await db.telegramBot.update({where:{id},data,include:{agent:{select:{name:true}},_count:{select:{allowlist:true,users:true}}}});if(updated.mode==='webhook'){try{const secret=updated.webhookSecretEncrypted?decryptSecret(updated.webhookSecretEncrypted):Buffer.from(randomBytes(24)).toString("hex");if(!updated.webhookSecretEncrypted)await db.telegramBot.update({where:{id},data:{webhookSecretEncrypted:encryptSecret(secret)}});const publicOrigin=(process.env.APP_PUBLIC_URL||new URL(req.url).origin).replace(/\/$/,'');if(!publicOrigin)throw new Error('آدرس عمومی برنامه برای Webhook تنظیم نشده است.');await setWebhook(token,publicOrigin+'/api/telegram/webhook/'+id,secret);await db.telegramBot.update({where:{id},data:{status:'connected',lastError:null}});}catch(e){await db.telegramBot.update({where:{id},data:{status:'error',lastError:e instanceof Error?e.message:'webhook error'}})}}else if(updated.mode==='polling'){await deleteWebhook(token).catch(()=>{});await db.telegramBot.update({where:{id},data:{status:'connected',lastError:null}})}await audit(bot.workspaceId,s.user.id,'telegram-bot.updated','telegram_bot',id,{fields:Object.keys(data)});return applyCors(jsonOk({bot:serialize(await load(s,id))}),req.headers.get('origin'));}catch(e){return toErrorResponse(e)}}
export async function DELETE(req:Request,{params}:Params){try{const s=await requireSession(req);const bot=await load(s,(await params).id);const m=assertWorkspaceAccess(s,bot.workspaceId);if(!['owner','admin'].includes(m.role))throw Object.assign(new Error('دسترسی حذف ربات ندارید.'),{status:403});await deleteWebhook(decryptSecret(bot.tokenEncrypted)).catch(()=>{});await db.telegramBot.delete({where:{id:bot.id}});await audit(bot.workspaceId,s.user.id,'telegram-bot.deleted','telegram_bot',bot.id);return applyCors(jsonOk({ok:true}),req.headers.get('origin'));}catch(e){return toErrorResponse(e)}}
