import { randomBytes } from '@/lib/server/random';
import { db } from '@/lib/db';
import { applyCors, jsonError, jsonOk, readJson, toErrorResponse } from '@/lib/server/http';
import { requireSession, assertWorkspaceAccess } from '@/lib/server/auth';
import { encryptSecret } from '@/lib/server/secrets';
import { audit } from '@/lib/server/audit';
import { loadAgentForSession } from '@/lib/server/access';
import { configureBotProfile, getBotInfo, setWebhook, deleteWebhook } from '@/lib/telegram/service';

export const dynamic='force-dynamic';
function serialize(b:any){return{id:b.id,name:b.name,agentId:b.agentId,agentName:b.agent.name,username:b.username,status:b.status,mode:b.mode,lastError:b.lastError,lastSeenAt:b.lastSeenAt?.toISOString()??null,createdAt:b.createdAt.toISOString(),updatedAt:b.updatedAt.toISOString(),allowlistCount:b._count.allowlist,usersCount:b._count.users}}
export async function GET(req:Request){try{const s=await requireSession(req);const workspaceId=new URL(req.url).searchParams.get('workspaceId')||s.memberships[0]?.workspaceId;if(!workspaceId)throw Object.assign(new Error('فضای کاری یافت نشد.'),{status:400});assertWorkspaceAccess(s,workspaceId);const bots=await db.telegramBot.findMany({where:{workspaceId},include:{agent:{select:{name:true}},_count:{select:{allowlist:true,users:true}}},orderBy:{createdAt:'desc'}});return applyCors(jsonOk({bots:bots.map(serialize)}),req.headers.get('origin'));}catch(e){return toErrorResponse(e)}}
export async function POST(req:Request){try{const s=await requireSession(req);const b=await readJson<Record<string,unknown>>(req);const workspaceId=typeof b.workspaceId==='string'?b.workspaceId:s.memberships[0]?.workspaceId;if(!workspaceId) throw Object.assign(new Error('فضای کاری یافت نشد.'),{status:400});const m=assertWorkspaceAccess(s,workspaceId);if(!['owner','admin'].includes(m.role)) throw Object.assign(new Error('دسترسی مدیریت ربات ندارید.'),{status:403});const agentId=typeof b.agentId==='string'?b.agentId:'';await loadAgentForSession(s,agentId);const name=typeof b.name==='string'?b.name.trim().slice(0,80):'ربات تلگرام';const token=typeof b.token==='string'?b.token.trim():'';const mode=typeof b.mode==='string'?b.mode:'webhook';if(mode!=='webhook') return applyCors(jsonError('در نسخه فعلی اتصال Telegram فقط با Webhook پشتیبانی می‌شود.',400),req.headers.get('origin'));if(!token) return applyCors(jsonError('Bot Token الزامی است.',400),req.headers.get('origin'));let info:any;try{info=await getBotInfo(token);}catch(e){return applyCors(jsonError('توکن یا اتصال Telegram معتبر نیست: '+(e instanceof Error?e.message:'خطای نامشخص'),502),req.headers.get('origin'));}const secret=cryptoRandom();const bot=await db.telegramBot.create({data:{workspaceId,agentId,name,tokenEncrypted:encryptSecret(token),username:info?.username??null,mode,status:'disconnected',webhookSecretEncrypted:encryptSecret(secret)}});await configureBotProfile(token,name);if(mode==='webhook'){try{const publicOrigin=(process.env.APP_PUBLIC_URL||new URL(req.url).origin).replace(/\/$/,'');if(!publicOrigin)throw new Error('آدرس عمومی برنامه برای Webhook تنظیم نشده است.');await setWebhook(token,publicOrigin+'/api/telegram/webhook/'+bot.id,secret);await db.telegramBot.update({where:{id:bot.id},data:{status:'connected'}});}catch(e){await db.telegramBot.update({where:{id:bot.id},data:{status:'error',lastError:e instanceof Error?e.message:'webhook error'}})}}await audit(workspaceId,s.user.id,'telegram-bot.created','telegram_bot',bot.id,{mode});return applyCors(jsonOk({bot:serialize({...bot,agent:{name:(await db.agent.findUniqueOrThrow({where:{id:agentId}})).name},_count:{allowlist:0,users:0}})},201),req.headers.get('origin'));}catch(e){return toErrorResponse(e)}}
function cryptoRandom() {
  return Buffer.from(randomBytes(24)).toString("hex");
}
