import { db } from "@/lib/db";
import { applyCors, jsonError, jsonOk, readJson, toErrorResponse } from "@/lib/server/http";
import { requireSession } from "@/lib/server/auth";
import { loadAgentForSession } from "@/lib/server/access";
import { ensureBuiltinTools } from "@/lib/runtime/tools";
export const dynamic = "force-dynamic";
export async function GET(req: Request, { params }: { params: Promise<{ id: string }> }) { try { const session=await requireSession(req); const {id}=await params; await loadAgentForSession(session,id); await ensureBuiltinTools(); const tools=await db.toolDefinition.findMany({where:{enabled:true},orderBy:{name:"asc"}}); const attached=await db.agentTool.findMany({where:{agentId:id},select:{toolId:true,enabled:true}}); const map=new Map(attached.map(x=>[x.toolId,x.enabled])); return applyCors(jsonOk({tools:tools.map(t=>({id:t.id,key:t.key,name:t.name,description:t.description,inputSchema:t.inputSchema,permissions:t.permissions,attached:map.get(t.id)===true}))}),req.headers.get("origin")); } catch(e){return toErrorResponse(e,req.headers.get("origin"));} }
export async function POST(req: Request,{params}:{params:Promise<{id:string}>}) { try { const session=await requireSession(req); const {id}=await params; await loadAgentForSession(session,id); const body=await readJson<{toolId?:unknown;enabled?:unknown}>(req); if(typeof body.toolId!=="string") return applyCors(jsonError("toolId الزامی است.",400),req.headers.get("origin")); const tool=await db.toolDefinition.findUnique({where:{id:body.toolId}}); if(!tool||!tool.enabled) return applyCors(jsonError("ابزار پیدا نشد.",404),req.headers.get("origin")); const row=await db.agentTool.upsert({where:{agentId_toolId:{agentId:id,toolId:tool.id}},update:{enabled:body.enabled!==false},create:{agentId:id,toolId:tool.id,enabled:body.enabled!==false}}); return applyCors(jsonOk({attachment:{id:row.id,toolId:row.toolId,enabled:row.enabled}}),req.headers.get("origin")); }catch(e){return toErrorResponse(e,req.headers.get("origin"));} }
export async function DELETE(req:Request,{params}:{params:Promise<{id:string}>}){try{const session=await requireSession(req);const {id}=await params;await loadAgentForSession(session,id);const toolId=new URL(req.url).searchParams.get("toolId");if(!toolId)return applyCors(jsonError("toolId الزامی است.",400),req.headers.get("origin"));await db.agentTool.deleteMany({where:{agentId:id,toolId}});return applyCors(jsonOk({ok:true}),req.headers.get("origin"));}catch(e){return toErrorResponse(e,req.headers.get("origin"));}}
