import { db } from "@/lib/db";
import { applyCors, jsonError, jsonOk, readJson, toErrorResponse } from "@/lib/server/http";
import { requireSession, assertWorkspaceAccess } from "@/lib/server/auth";
import { audit } from "@/lib/server/audit";
import { normalizeTelegramPhone } from "@/lib/telegram/phone";
export const dynamic='force-dynamic';
type Params={params:Promise<{id:string}>};

export async function GET(req:Request,{params}:Params){try{const s=await requireSession(req);const bot=await db.telegramBot.findUnique({where:{id:(await params).id}});if(!bot)throw Object.assign(new Error('ربات یافت نشد.'),{status:404});assertWorkspaceAccess(s,bot.workspaceId);const entries=await db.telegramAllowlistEntry.findMany({where:{botId:bot.id},orderBy:{createdAt:'desc'}});return applyCors(jsonOk({entries}),req.headers.get('origin'));}catch(e){return toErrorResponse(e)}}
export async function POST(req:Request,{params}:Params){try{const s=await requireSession(req);const bot=await db.telegramBot.findUnique({where:{id:(await params).id}});if(!bot)throw Object.assign(new Error('ربات یافت نشد.'),{status:404});const m=assertWorkspaceAccess(s,bot.workspaceId);if(!['owner','admin'].includes(m.role))throw Object.assign(new Error('دسترسی مدیریت فهرست کاربران ندارید.'),{status:403});const b=await readJson<Record<string,unknown>>(req);const phone=typeof b.phoneNumber==='string'?normalizeTelegramPhone(b.phoneNumber):'';if(phone.length<8)return applyCors(jsonError('شماره موبایل معتبر نیست.',400),req.headers.get('origin'));const entry=await db.telegramAllowlistEntry.upsert({where:{botId_phoneNumber:{botId:bot.id,phoneNumber:phone}},update:{displayName:typeof b.displayName==='string'?b.displayName.trim().slice(0,80):null,notes:typeof b.notes==='string'?b.notes.trim().slice(0,300):null,status:'allowed'},create:{botId:bot.id,phoneNumber:phone,displayName:typeof b.displayName==='string'?b.displayName.trim().slice(0,80):null,notes:typeof b.notes==='string'?b.notes.trim().slice(0,300):null,status:'allowed'}});await db.telegramUser.updateMany({where:{botId:bot.id,phoneNumber:phone},data:{status:'allowed'}});await audit(bot.workspaceId,s.user.id,'telegram-allowlist.added','telegram_allowlist',entry.id,{phoneNumber:phone});return applyCors(jsonOk({entry},201),req.headers.get('origin'));}catch(e){return toErrorResponse(e)}}
export async function DELETE(req:Request,{params}:Params){try{const s=await requireSession(req);const bot=await db.telegramBot.findUnique({where:{id:(await params).id}});if(!bot)throw Object.assign(new Error('ربات یافت نشد.'),{status:404});const m=assertWorkspaceAccess(s,bot.workspaceId);if(!['owner','admin'].includes(m.role))throw Object.assign(new Error('دسترسی ندارید.'),{status:403});const entryId=new URL(req.url).searchParams.get('entryId');if(!entryId)return applyCors(jsonError('entryId الزامی است.',400),req.headers.get('origin'));const entry=await db.telegramAllowlistEntry.findUnique({where:{id:entryId}});if(!entry||entry.botId!==bot.id)return applyCors(jsonError('کاربر پیدا نشد.',404),req.headers.get('origin'));await db.telegramAllowlistEntry.delete({where:{id:entry.id}});
await db.telegramUser.updateMany({where:{botId:bot.id,phoneNumber:entry.phoneNumber},data:{status:'blocked'}});
return applyCors(jsonOk({ok:true}),req.headers.get('origin'));}catch(e){return toErrorResponse(e)}}
